//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace CarDealer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public class CarDetail
    {
        [Key]
        public long CarId { get; set; }
        [DataType(DataType.DateTime)]
        public Nullable<System.DateTime> FirstRegistrationDate { get; set; }
        public string MoreImage { get; set; }
        public string Feature { get; set; }
        [Range(0,200)]
        public Nullable<byte> NumberOfSeat { get; set; }
        [Range(0, 200)]
        public Nullable<byte> NumberOfDoor { get; set; }
        [Range(0,10000)]
        public int? CupicCapacity { get; set; }
        [Range(0,5000)]
        public int Horsepower { get; set; }
        [Range(0,100)]
        public Nullable<byte> Cylider { get; set; }

        public string FuelType { get; set; }
        [Range(0,200)]
        public Nullable<byte> FuelConsumption { get; set; }


        public Nullable<System.DateTime> ModifiedOn { get; set; }
       
        public string ModifiedBy { get; set; }
        public string TranmisionType { get; set; }
        public string EmissionClass { get; set; }
        public string InteriorColor { get; set; }
        public string ExteriorColor { get; set; }
        public string WheelType { get; set; }
        [DataType(DataType.MultilineText)]
        [AllowHtml]
        public string SellerNote { get; set; }

        // public virtual Car ToCar { get; set; }
    }
}
