//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations.Schema;

namespace CarDealer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class CarModel
    {
        [Key]
        public int ID { get; set; }
        [Display(Name ="Model Name")]
        public string Name { get; set; }
        public string MetaTitle { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public string SeoTitle { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifeeDate { get; set; }
        public string ModifieBy { get; set; }
        public string MetaKeywords { get; set; }
        public string MetaDescriptions { get; set; }
        public int Waranty { get; set; }
        
        public Nullable<int> ManufactureId { get; set; }
        [ForeignKey("ManufactureId")]
        public virtual Manufacture ToManufacture { get; set; }

        public virtual  ICollection<Car> ToCars { get; set; }

    }
}
