//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealer.Models
{
    using Microsoft.AspNet.Identity.EntityFramework;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public class CarSold
    {
        [Key]
        public long CarSoldId { get; set; }
        [Required]
        public long CarId { get; set; }
        
        public string UserId { get; set; }
        [Display(Name ="Customer Name")]
        public string Name  { get; set; }
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }
        [Required]
        [DataType(DataType.PhoneNumber, ErrorMessage = "Provided phone number not valid")]
        [RegularExpression(@"^(\d)+$", ErrorMessage = "Wrong mobile")]
        [StringLength(13,MinimumLength =10)]
        public string PhoneNumber { get; set; }
        [Required]
        [Range(0,1000000)]
        public Nullable<decimal> AgreedPrice { get; set; }
        [DataType(DataType.Date)]
        [Required]
        
        public Nullable<System.DateTime> Datesold { get; set; }
        [Required]
        public int PaymentStatus { get; set; }
        [Required]
        public string PaymentMethod { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PaymentStartDate { get; set; }
        [DataType(DataType.Date)]
        public Nullable<System.DateTime> PaymentEndDate { get; set; }
        [Range(0, 1000000)]
        public Nullable<decimal> ActurePaymentAmount { get; set; }
        public string OtherDetail { get; set; }

        //[ForeignKey("UserId")]
        //public virtual ApplicationUser ToUser { get; set; }

        [ForeignKey("CarId")]
        public virtual Car ToCar { get; set; }


    }
}
