//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Footter
    {
        [Key]
        public int ID { get; set; }
        [DataType(DataType.MultilineText)]
        public string Content { get; set; }
        public Nullable<bool> Status { get; set; }
    }
}
