//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarDealer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public class Manufacture
    {
        [Key]
        public int ManufactureId { get; set; }
        public string FullName { get; set; }
        public string ShortName { get; set; }
        public string Detail { get; set; }

        public virtual ICollection<CarModel> ToModels { get; set; }
    }
}
